#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaPro.DataClases
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="teamdinamita")]
	public partial class DataClassesResumenDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClassesResumenDataContext() : 
				base(global::MetaPro.Properties.Settings.Default.teamdinamitaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesResumenDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesResumenDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesResumenDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesResumenDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Agregar_Amigo")]
		public ISingleResult<SP_Agregar_AmigoResult> SP_Agregar_Amigo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string buscar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), buscar);
			return ((ISingleResult<SP_Agregar_AmigoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Añadir_Amigo")]
		public ISingleResult<SP_Añadir_AmigoResult> SP_Añadir_Amigo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string buscar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), buscar);
			return ((ISingleResult<SP_Añadir_AmigoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LoginUsuario")]
		public ISingleResult<SP_LoginUsuarioResult> SP_LoginUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string pusuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string ppassword)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pusuario, ppassword);
			return ((ISingleResult<SP_LoginUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VerMiProgreso")]
		public ISingleResult<SP_VerMiProgresoResult> SP_VerMiProgreso([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ObjetivoID", DbType="Int")] System.Nullable<int> objetivoID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), objetivoID);
			return ((ISingleResult<SP_VerMiProgresoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VerMisObjetivos")]
		public ISingleResult<SP_VerMisObjetivosResult> SP_VerMisObjetivos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID);
			return ((ISingleResult<SP_VerMisObjetivosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VerListaAmigos")]
		public ISingleResult<SP_VerListaAmigosResult> SP_VerListaAmigos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID);
			return ((ISingleResult<SP_VerListaAmigosResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_Agregar_AmigoResult
	{
		
		private int _IdUsuario;
		
		private string _Nickname;
		
		private string _Pais;
		
		private string _Sexo;
		
		public SP_Agregar_AmigoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this._Nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this._Pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this._Sexo = value;
				}
			}
		}
	}
	
	public partial class SP_Añadir_AmigoResult
	{
		
		private string _Nickname;
		
		private string _Pais;
		
		private string _Sexo;
		
		public SP_Añadir_AmigoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this._Nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this._Pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this._Sexo = value;
				}
			}
		}
	}
	
	public partial class SP_LoginUsuarioResult
	{
		
		private int _IdUsuario;
		
		private string _Nickname;
		
		private string _Contraseña;
		
		public SP_LoginUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this._Nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
	}
	
	public partial class SP_VerMiProgresoResult
	{
		
		private int _Avance;
		
		private System.DateTime _DiaProgreso;
		
		public SP_VerMiProgresoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avance", DbType="Int NOT NULL")]
		public int Avance
		{
			get
			{
				return this._Avance;
			}
			set
			{
				if ((this._Avance != value))
				{
					this._Avance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaProgreso", DbType="Date NOT NULL")]
		public System.DateTime DiaProgreso
		{
			get
			{
				return this._DiaProgreso;
			}
			set
			{
				if ((this._DiaProgreso != value))
				{
					this._DiaProgreso = value;
				}
			}
		}
	}
	
	public partial class SP_VerMisObjetivosResult
	{
		
		private string _Titulo;
		
		private string _Descripcion;
		
		private int _Tiempo;
		
		private System.DateTime _FechaC;
		
		private int _Avance;
		
		private string _Dificultad;
		
		private int _IdObjetivo;
		
		public SP_VerMisObjetivosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this._Titulo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiempo", DbType="Int NOT NULL")]
		public int Tiempo
		{
			get
			{
				return this._Tiempo;
			}
			set
			{
				if ((this._Tiempo != value))
				{
					this._Tiempo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaC", DbType="Date NOT NULL")]
		public System.DateTime FechaC
		{
			get
			{
				return this._FechaC;
			}
			set
			{
				if ((this._FechaC != value))
				{
					this._FechaC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avance", DbType="Int NOT NULL")]
		public int Avance
		{
			get
			{
				return this._Avance;
			}
			set
			{
				if ((this._Avance != value))
				{
					this._Avance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dificultad", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Dificultad
		{
			get
			{
				return this._Dificultad;
			}
			set
			{
				if ((this._Dificultad != value))
				{
					this._Dificultad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdObjetivo", DbType="Int NOT NULL")]
		public int IdObjetivo
		{
			get
			{
				return this._IdObjetivo;
			}
			set
			{
				if ((this._IdObjetivo != value))
				{
					this._IdObjetivo = value;
				}
			}
		}
	}
	
	public partial class SP_VerListaAmigosResult
	{
		
		private int _IdAmigoUsuario;
		
		private string _Nickname;
		
		private string _Conexion;
		
		public SP_VerListaAmigosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAmigoUsuario", DbType="Int NOT NULL")]
		public int IdAmigoUsuario
		{
			get
			{
				return this._IdAmigoUsuario;
			}
			set
			{
				if ((this._IdAmigoUsuario != value))
				{
					this._IdAmigoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nickname", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Nickname
		{
			get
			{
				return this._Nickname;
			}
			set
			{
				if ((this._Nickname != value))
				{
					this._Nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conexion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Conexion
		{
			get
			{
				return this._Conexion;
			}
			set
			{
				if ((this._Conexion != value))
				{
					this._Conexion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
